[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
flanterm_bindings = "1.1.4"
limine = "0.4"
crossbeam-queue = { version = "0.3.12", default-features = false, features = ["alloc"] }
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
pc-keyboard = "0.8.0"
spin = "0.10.0"
x86_64 = "0.15.2"
talc = "4.4.2"

[features]
default = []
tests = []
