[package]
name = "chronos"
version = "0.1.0"
authors = ["bugo07"]
edition = "2024"

[profile.dev]
opt-level = 1
lto = "thin" # makes performance 10x with no noticable difference in compile time

[profile.release]
opt-level = 1 # bootloop on 2 and 3 // "z" sometimes has better performance
codegen-units = 1
strip = true
lto = "fat"

[profile.smol]
inherits = "release"
opt-level = "z"
codegen-units = 1
strip = true
lto = "fat"

[dependencies]
limine = "0.4"
# tomling = { version = "0.2.0", default-features = false }
conquer-once = { version = "0.4.0", default-features = false }
crossbeam-queue = { version = "0.3.12", default-features = false, features = ["alloc"] }
futures-util = { version = "0.3.31", default-features = false, features = ["alloc"] }
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
pc-keyboard = "0.8.0"
spin = "0.10.0"
talc = "4.4.2"
mmio = "2.1.0"
uacpi-sys = { path = "../bindings/uacpi-sys" }
flanterm-sys = { path = "../bindings/flanterm-sys" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64 = "0.0.14"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.15.2"
ps2-mouse = "0.1.4"

[features]
# default = ["tests"] # to get intelisense on test files
tests = []
uacpi_test = []
